blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	#Home page
	path('', views.index, name='index'),
	path('blog/', views.blog, name='blog'),
	path('blog/<int:entry_id>/', views.entry, name='entry'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
	path('', views.contact_me, name='contact_me'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('projects/', include('projects.urls')),
]

projects/urls.py
from django.urls import path
from . import views

app_name='projects'

urlpatterns = [
	path('', views.project_index, name='project_index'),
]

blog/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):

	title = models.CharField(max_length=200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		return f'{self.text[:50]}...'

class Comment(models.Model):

	entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)

	class Meta:
		ordering = ['created_on']

	def __str__(self):
		return f'Comment {self.body} by {self.name}'

contact/models.py
from django.db import models
reason_for_email = [
	('greeting', 'Just saying Hi!'),
	('work', "Business"), 
	('ideas', 'Ideas'),
	('hm', 'Hate mail'), 
	('bored', 'Other'),
]
# Create your models here.
class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=200)
	reason = models.CharField(choices=reason_for_email, default ='Just saying Hi!' ,max_length=50)
	subject = models.CharField(max_length=200)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Contact"

	def __str__(self):
		return f'{self.name}-{self.email}'

projects/models.py
from django.db import models

# Create your models here.

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Entry
from .forms import CommentForm

# Create your views here.
def index(request):
	context = {
		'twitter_url': "https://twitter.com/oh_aobakwe", 
		'instagram_url': "https://instagram.com/aobakweokay",
		'github_url': "https://github.com/OkayAobakwe",
	}
	return render(request, 'blog/index.html', context)

def blog(request):
	entries = Entry.objects.order_by('date_added')
	context = {
		'entries': entries
	}
	return render(request, 'blog/blog.html', context)

def entry(request, entry_id):
	entry = Entry.objects.get(id=entry_id)
	comments = entry.comments.filter(active=True)
	new_comment = None

	if request.method != "POST":
		comment_form = CommentForm()
	else:
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.entry = entry
			new_comment.save()

	context ={'entry': entry, 'comments': comments, 'new_comment': new_comment,
				'comment_form': comment_form,}
	return render(request, 'blog/entry.html', context)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm

# Create your views here.
def contact_me(request):
	if request.method != 'POST':
		form = ContactForm()
	else:
		form = ContactForm(data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blog:index')

	context = { 'form': form}
	return render(request, 'contact/contact_me.html', context)

projects/views.py
from django.shortcuts import render


# Create your views here.
def project_index(request):
	context = {'my_url': "https://sand-logs.herokuapp.com/"}
	return render(request, 'projects/project_index.html', context)

blog/templates/blog/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang='en'>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale-1,
	shrink-to-fit=no">
	<title>Aobakwe</title>
	{% load static %}
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
</head>
<body style="font-family:'Poppins'; position: relative;">
	<nav class="navbar navbar-expand-md border bg-light navbar-light">
		<a class="navbar-brand" href="{% url 'blog:index' %}">Aobakwe</a> 
		<button class="navbar-toggler" type='button' data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'projects:project_index' %}">Projects</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'contact:contact_me' %}">Contact me</a>
				</li>
			</ul>
		</div>
	</nav>
	<main role="main" class="container" style="min-height: 100%; padding-bottom: 2.5rem; position: relative;">
		{% block content %}{% endblock %}
	</main>
	<footer class="footer card-footer" style="bottom: 0; width: 100%; height:2.5rem; position: absolute;">
   		<div class="footer-copyright text-center">Copyright: 2020</div>
  	</footer>
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block content %}
	<div style="min-height: 85vh">
		<h2>Entries</h2>

		<ul>
			{% for entry in entries %}
				<div class="card mb-3">
					<h3 class='card-header'>
						<a href="{% url 'blog:entry' entry.id %}" class="text-dark">{{entry.title}}
						</a>
					</h3>
					<div class="card-body">
						{{entry.text | slice:":400"}}...
					</div>
				</div>
			{% empty %}
				<li>No entries yet</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

blog/templates/blog/entry.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}
{% block content %}
	<div class="container" style="min-height: 85vh; padding-bottom: 2.5rem;">
		<h3>{{entry.title}}</h3>
		<h5 class="mb-30">{{entry.date_added|date:'M d, Y H:i'}}</h5>
		<p>{{entry.text|linebreaks}}</p>
		<div>
      		<div class="card-body">
        		<h2>{{ comments.count }} comments</h2>

        		{% for comment in comments %}
        			<div class="comments" style="padding: 10px;">
         		 		<p class="font-weight-bold">
            				{{ comment.name }}
            				<span class=" text-muted font-weight-normal">
              					{{ comment.created_on }}
            				</span>
          				</p>
          				{{ comment.body | linebreaks }}
        			</div>
        			{% endfor %}
      		</div>
    	</div>
    	<div>
      		<div class="card-body">
        		{% if new_comment %}
        			<div class="alert alert-success" role="alert">
         				Your comment is awaiting moderation
        			</div>
        		{% else %}
        			<h3>Leave a hate comment</h3>
        			<form method="post" style="margin-top: 1.3em;" class="form">
          				{% csrf_token %}
          				{% bootstrap_form comment_form %}
          				{% buttons %}
          					<button name="submit" class="btn btn-dark">Submit</button>
          				{% endbuttons %}
        			</form>
        		{% endif %}
      		</div>
    	</div>
	</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
  <div class='container' style="min-height: 50vh; min-width:82vw; padding-bottom: 2.5rem;">
    <div class="row">
      <div class="col bg-dark">
        <img src="{% static 'img/hero2.png'%}" style="height:69vh; max-width:82vw;" class="mx-auto d-block">
      </div>
      <div class="col bg-light d-flex align-items-center" style="height:">  
        <h4>Self learning software developer, also a human being(believe it or not), I am probably funny.<br/>I am likely to document all that in my blogs, as I try to display my interests in electronics, machine learning, game dev and network security... yeah that is too much, I agree.<br/><br/> 
        </h4>
      </div>
    </div>
    <div class="mt-4">
      <h4>
        <ul class="list-unstyled list-inline text-center">
          <li class="list-inline-item">
            <a href="{{ twitter_url }}" class='text-dark'><i class="fa fa-twitter"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="{{ instagram_url }}" class='text-dark'><i class="fa fa-instagram"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="{{ github_url }}" class='text-dark'><i class="fa fa-github"></i></a>
          </li>
        </ul>
      </h4>
    </div>
  </div>

{% endblock %}

contact/templates/contact/contact_me.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}
{% block content %}
	<h2>Contact Me:</h2>

	<form action="{% url 'contact:contact_me' %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-dark">Contact</button>
		{% endbuttons %}
	</form>
{% endblock %}

projects/templates/projects/project_index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<h2 class=" border-bottom mb-2 pb-2">Projects</h2>
<div style="min-height: 85vh; padding-bottom: 2.5rem;">
	<h5>Learning Log</h5>
	<img src="{% static 'img/project1.jpg' %}" style="height:50vh; width:50vh;">
	<h5>About the project:</h5>
	<p><a href="{{ my_url }}" class="text-decoration-none">Link</a></p>
	<p>Learning log is a web application that allows users to track their learning on topics of their interests.</p>
	<h5>Technology</h5>
	<p>Django and Bootstrap4</p>
</div>
{% endblock %}